#!/usr/bin/env python3
"""
generate_diagram.py

Reads the entity definitions in els-data-model (validating each one against its JSON Schema) and generates a single markdown file
with Entity-Relationship Diagram.

Usage:
    python generate_full_schema.py
    python generate_full_schema.py --model-dir ../../../els-data-model --output /path/to/out.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import jsonschema
except ImportError:
    sys.exit(
        "The 'jsonschema' package is required but is not installed.\n"
        "Install it with:\n"
        "    pip install -r requirements.txt"
    )

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_MODEL_DIR = (SCRIPT_DIR / ".." / "..").resolve()
DEFAULT_OUTPUT = (SCRIPT_DIR / ".." / ".." / "diagrams" / "wip" / "erd.md").resolve()


def load_entities(model_dir: Path) -> list[dict]:
    """Load every entity definition, validate it against the model's JSON Schema, and return
    them sorted by entity name.

    Sorting immediately after loading (rather than relying on filesystem/glob order) is what
    makes every downstream statement order deterministic and stable under insertion: two entities'
    relative order depends only on comparing their two names, never on what else exists or when
    things were added.
    """
    schema_path = model_dir / "model" / "schema" / "model.schema.json"
    entities_dir = model_dir / "model" / "entities"

    if not schema_path.exists():
        raise FileNotFoundError(f"Schema not found at {schema_path}")
    if not entities_dir.is_dir():
        raise FileNotFoundError(f"Entities folder not found at {entities_dir}")

    schema = json.loads(schema_path.read_text(encoding="utf-8"))

    entities = []
    for entity_file in entities_dir.glob("*.json"):
        entity = json.loads(entity_file.read_text(encoding="utf-8"))
        try:
            jsonschema.validate(entity, schema)
        except jsonschema.exceptions.ValidationError as e:
            # Re-raise with the source filename attached — the raw error's `instance` may be a
            # nested part of the document (e.g. one column), not the whole entity, so it can't
            # reliably be used to name which entity file is at fault.
            raise jsonschema.exceptions.ValidationError(
                f"{entity_file.name}: {e.message}"
            ) from e
        entities.append(entity)

    if not entities:
        raise ValueError(f"No entity definitions found in {entities_dir}")

    entities.sort(key=lambda e: e["entity"])
    return entities

def render_column(column: dict) -> str:
    # Null clause is ? but it is not supported by VS Code built-in preview yet.
    # It requires Mermaid 11.16+ which is available on GitHub but not in VS Code.
    null_clause = "" if column.get("nullable", False) else ""
    pk_clause = " PK" if column.get("primaryKey", False) else ""
    fk_clause = " FK" if column.get("foreignKey", False) else ""
    keys_clause = ", ".join(filter(None, (pk_clause, fk_clause)))
    short_description = column.get("shortDescription", "")
    comment_clause = f' "{build_comment(short_description)}"' if short_description else ""

    return f"        {column['type']}{null_clause} {column['name']}{keys_clause}{comment_clause}"


def render_entity_detail(entity: dict) -> str:
    table = entity['table'].upper()
    lines = [render_column(column) for column in entity["columns"]]

    body = "\n".join(lines)
    return f"    {table} {{\n{body}\n    }}\n"


def render_relations(entity: dict, table_by_entity: dict[str, str]) -> list[str]:
    """Foreign keys are emitted as relations."""

    table = entity['table'].upper()
    relations = []
    for column in entity["columns"]:
        fks = column.get("foreignKeys")
        if not fks:
            continue
        for fk in fks:
            ref_table = table_by_entity[fk["entity"]].upper()
            ref_relation = fk.get("relation", "xx")
            relation = f'    {ref_table} ||--o{{ {table} : "{ref_relation}"'

            if relation not in relations:
                relations.append(relation)
    return relations


def build_comment(value: str) -> str:
    """Mermaid ERD comments can't contain double quotes. And we also restrict length to avoid formatting issues."""
    return value.replace('"', "'")[:100]


def generate_markdown(entities: list[dict]) -> str:
    table_by_entity = {e["entity"]: e["table"] for e in entities}

    parts = [
        "# Entity-Relationship Diagram",
        "",
        "Auto-generated by scripts/generate-diagram/generate_diagram.py. Do not edit by hand.",
        "- Source: els-data-model/model/entities/*.json",
        "- Regenerate with: python generate_diagram.py",
        "",
        "Rendered with [Mermaid](https://mermaid.js.org/), which GitHub renders natively inside Markdown — no extra tooling needed to view it.",
        "",
        "```mermaid",
        "erDiagram",
    ]

    for entity in entities:
        parts.append(render_entity_detail(entity))

    relations = []
    for entity in entities:
        relations.extend(render_relations(entity, table_by_entity))

    if relations:
        parts.append("")
        parts.extend(relations)

    parts.append("```")

    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--model-dir", type=Path, default=DEFAULT_MODEL_DIR,
        help="Path to the els-data-model component (default: %(default)s)",
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="Path to write the generated .sql file to (default: %(default)s)",
    )
    args = parser.parse_args()

    try:
        entities = load_entities(args.model_dir)
        markdown = generate_markdown(entities)
    except jsonschema.exceptions.ValidationError as e:
        print(f"Entity validation failed: {e.message}", file=sys.stderr)
        return 1
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(markdown)

    print(f"Wrote {len(entities)} Entities to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
